---
title: "Sharla Gelfand"
author: Sharla Gelfand
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results = "asis",
  echo = FALSE
)

library(glue)
library(dplyr)
library(purrr)
library(tidyr)
library(stringr)
library(readr)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source("parsing_functions.R")

# Load csv with position info
position_data <- read_delim("positions.csv", ";", escape_double = FALSE, trim_ws = TRUE)
```


```{r}
# When in export mode the little dots are unaligned, so fix that.
if (PDF_EXPORT) {
  cat("
  <style>
  :root{
    --decorator-outer-offset-left: -6.5px;
  }
  </style>")
}
```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------


- <i class="fa fa-envelope"></i> sharla.gelfand@gmail.com
- <i class="fa fa-twitter"></i> sharlagelfand
- <i class="fa fa-github"></i> [github.com/sharlagelfand](https://github.com/sharlagelfand)
- <i class="fa fa-link"></i> [sharla.party](http://sharla.party/)

Language Skills {#skills}
--------------------------------------------------------------------------------

- <i class="fa fa-laptop"></i> R (tidyverse, base R, Shiny, package development)
- <i class="fa fa-database"></i> SQL (MySQL, Postgres, BigQuery)
- <i class="fa fa-github-alt"></i> git (and GitHub)

Main
================================================================================

Sharla Gelfand {#title}
--------------------------------------------------------------------------------


```{r}
intro_text <- "I am a statistician and an R and Shiny developer. My work focuses on developing tools that enable easier access to data (such as my R package, [opendatatoronto](https://sharlagelfand.github.io/opendatatoronto)) and replacing manual, repetitive work with reproducible and future-proof processes. I write about R at [sharla.party](https://sharla.party) and love contributing to open source."

cat(sanitize_links(intro_text))
```

Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, "experience")
```

<br>

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, "education")
```

Talks {data-icon=book}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, "talks")
```

```{r}
if (PDF_EXPORT) {
  cat("
  
Links {data-icon=link}
--------------------------------------------------------------------------------

<br>


")

  walk2(links, 1:length(links), function(link, index) {
    print(glue("{index}. {link}"))
  })
}
```

Community {data-icon=hands-helping}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, "community")
```

```{r}
if (PDF_EXPORT) {
  cat("
  
Links {data-icon=link}
--------------------------------------------------------------------------------

<br>


")

  walk2(links, 1:length(links), function(link, index) {
    print(glue("{index}. {link}"))
  })
}
```
